### ISSUE TITLE
runtime.js:  TypeError: value is undefined

### ISSUE THREAD

**Issue by darkwing** [darkowlzz/zest-runner#28]
I've been working on an add-on which will utilize zest-runner:

https://github.com/mozilla/mdn-devtool

When I import the following zest file:

https://gist.github.com/darkwing/58721e34bd6c31ccc0a9

I receive the following error:

https://gist.github.com/darkwing/919269905f01ad78c759

**Comment by darkwing** [comment]
Oddly enough, after that initial error, if I import and run a second time, I get some form of result:

https://gist.github.com/darkwing/b809da536a24e2008e67

**Comment by darkowlzz** [comment]
hi @darkwing , so I tried the script and found that "value is undefined" is due to undefined variables in the script, like [this] one (`request.url`). In such situation, zest should prompt to define those values. Give me some time to make zest return some error code which the client could use to identify what's required and prompt the user to provide those values.

Thanks for raising the issue.

[this]: https://gist.github.com/darkwing/58721e34bd6c31ccc0a9#file-gistfile1-js-L24

**Comment by darkwing** [comment]
Great!
